### DISCUSSION TITLE
Nginx reverse proxy Homebox to a subfolder

### DISCUSSION THREAD

**Discussion by gaellecoz** [sysadminsmedia/homebox#322] [Q&A] [answered]
Hello everyone,

First of all thank you for maintaining this app, I just started to use it and it really fits my needs.

However in hosting it myself I want to host it in a subfolder of my domain, e.g. mydomain.com/homebox. I host all my apps this way so I can use the same TLS certificate for all of them.

To test it I setup homebox and docker this way.

**docker-compose.yml**
```
    services:
        homebox:
            image: homebox
            build:
                context: .
                dockerfile: ./Dockerfile
                args:
                  - COMMIT=head
                  - BUILD_TIME=0001-01-01T00:00:00Z
            ports:
              - 3100:7745
            networks:
              - proxy
    
    nginx:
        image: nginx:latest
        container_name: nginx
        volumes:
          - ./nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
          - 80:80
        links:
          - homebox
        networks:
          - proxy
      
     networks:
       proxy:
```

**nginx.conf**
```
    server { 
      listen 80 default_server;
      listen [::]:80 default_server;
      server_name _;
      
      # Configuration for Homebox
     location ^~ /homebox {
        proxy_redirect off;
        proxy_buffering off;
        
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_set_header X-NginX-Proxy true;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
          
        sub_filter 'src="'  'src="/homebox/';
        sub_filter 'href="'  'href="/homebox/';
        sub_filter_once off;
        sub_filter_types *;
        proxy_pass         http://homebox-homebox-1:7745/;
    }
    } 
```
It starts to load but I end up with a 404 screen
![Screenshot 2024-11-04 at 21 52 03](https://github.com/user-attachments/assets/cf1f1148-5edf-4a42-b73b-11a8dfc14aab)

I also tried to edit `frontend/nuxt.config.ts` and add this entry at the beginning:
```
    app: {
        baseURL: '/homebox/'
      },
```
But it did not yield much result.

Does anyone have an idea how to do it?

Kind regards
