### DISCUSSION TITLE
Health Check fails in Rootless container when run as specific user

### DISCUSSION THREAD

**Discussion by Mngnt** [sysadminsmedia/homebox#338] [Support]
### First Check

- [x] This is not a feature request
- [x] I added a very descriptive title to this issue.
- [x] I used the GitHub search to find a similar issue and didn't find it.
- [x] I searched the documentation, with the integrated search.
- [x] I already read the docs and didn't find an answer.
- [x] I can replicate the issue inside the Demo install.

### Homebox Version

0.15.2-rootless

### What is the issue you are experiencing?

When running the rootless container and specifying the user in my compose file, the health check fails with a "Permission denied" error.  This appears to be due to the filesystem within the container.

```
root@alpha:~/alpha# cat homebox-compose.yaml
services:
  homebox:
    image: ghcr.io/sysadminsmedia/homebox:latest-rootless
    user: 1001:1001
    container_name: homebox
    restart: unless-stopped
    environment:
    - HBOX_LOG_LEVEL=info
    - HBOX_LOG_FORMAT=text
    - HBOX_WEB_MAX_UPLOAD_SIZE=10
    volumes:
      - /SSD/homebox:/data/
    ports:
      - 3100:7745


```

EDIT: previous information posted here was incorrect - please see below for additional healthcheck error log output.

### How can the maintainer reproduce the issue?

Run via compose file above; observe the container remaining in "unhealthy" state.

### Deployment

Docker (Linux)

### OS Architechture

x86_64 (AMD, Intel)
