### DISCUSSION TITLE
Homebox creates and immediately clears auth cookie resulting in logout when connecting via https://domain using reverse proxy

### DISCUSSION THREAD

**Discussion by stamonty** [sysadminsmedia/homebox#458] [Support] [answered]
### First Check

- [x] This is not a feature request
- [x] I added a very descriptive title to this issue.
- [x] I used the GitHub search to find a similar issue and didn't find it.
- [x] I searched the documentation, with the integrated search.
- [x] I already read the docs and didn't find an answer.
- [x] I can replicate the issue inside the Demo install.

### Homebox Version

v0.17.2

### What is the issue you are experiencing?

Homebox creates and immediately clears auth cookie resulting in logout after trying to view any internal page.
`ERR ../go/src/app/internal/web/mid/errors.go:31 > ERROR occurred error="authorization header or query is required" `

I use rootless image of Homebox

Many thanks.

### How can the maintainer reproduce the issue?

1. Register a new account
2. Log in and try to view any page, locations, for example.

### Deployment

Docker (Linux)

### OS Architechture

x86_64 (AMD, Intel)

### Deployment Details

Docker compose

```
services:
  homebox:
    container_name: homebox
    image: ghcr.io/sysadminsmedia/homebox:latest-rootless
    #pull_policy: never
    volumes:
      - data:/data
    env_file:
      - .env
    ports:
      - 3100:7745
    restart: unless-stopped
volumes:
  data:
```
.env
```
HBOX_MODE=development
HBOX_LOG_LEVEL=debug
HBOX_LOG_FORMAT=text
HBOX_OPTIONS_ALLOW_REGISTRATION=false
```
Env in the Homebox container
```
/app $ printenv
HOSTNAME=fedf31a40838
HBOX_STORAGE_DATA=/data/
SHLVL=1
HOME=/home/nonroot
HBOX_MODE=development
HBOX_OPTIONS_ALLOW_REGISTRATION=false
TERM=xterm
HBOX_STORAGE_SQLITE_URL=/data/homebox.db?_pragma=busy_timeout=2000&_pragma=journal_mode=WAL&_fk=1&_time_format=sqlite
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HBOX_LOG_LEVEL=debug
HBOX_LOG_FORMAT=text
PWD=/app
```
Version: v0.17.2 ~ Build: 44bdca8c212a6d4ae1e500e59d14587c9cadc17e

Please let me know if you need any additional info
