### DISCUSSION TITLE
Separate config & data paths in docker?

### DISCUSSION THREAD

**Discussion by crispybegs** [sysadminsmedia/homebox#672] [Q&A] [answered]
Is it possible to separate out the HB config from heavier data like photos etc? Most of my services do this, where my app configs are stored, for example, in `/home/crispy/docker/homebox/config` which is a relatively small drive and the data is stored on a larger drive elsewhere e.g. `/media/drive_1/apps/homebox/data`

so my compose would look something like:

```
services:
  homebox:
    image: ghcr.io/sysadminsmedia/homebox:latest
    container_name: homebox
    restart: unless-stopped
    environment:
    - HBOX_LOG_LEVEL=info
    - HBOX_LOG_FORMAT=text
    - HBOX_WEB_MAX_UPLOAD_SIZE=10
    volumes:
      - /home/crispy/docker/homebox/config:/data/
      - /media/drive_1/apps/homebox/data:/media/
    ports:
      - 3100:7745

volumes:
   homebox-data:
     driver: local
```
