### ISSUE TITLE
0.12 doesn't work with Traefik Reverse Proxy

### ISSUE THREAD

**Issue by brhahlen** [sysadminsmedia/homebox#107]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### Homebox Version

0.12.0

### What is the issue you are experiencing?

Version 0.12.0 of HomeBox breaks  "something" (and I don't know what) that makes it not work with Traefik.
The exact same configuration works with 0.11.1 (and older versions).

Also tried with main and main-rootless

### How can the maintainer reproduce the issue?

Compose:
``` 
  homebox:
    extends:
      file: ../shared.yml
      service: pubnet-shared
    container_name: homebox
    # image: ghcr.io/sysadminsmedia/homebox:0.11
    image: ghcr.io/sysadminsmedia/homebox:main-rootless
    env_file: homebox.env
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONF_DIR}/homebox:/data/
    labels:
      ## Traefik
      - "traefik.enable=true"
      - "traefik.docker.network=lan_net"
      ## HTTP Routers
      - "traefik.http.routers.homebox.entrypoints=web-secure"
      - "traefik.http.routers.homebox.rule=Host(`homebox.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.homebox.middlewares=ipallowlist"
      ## HTTP Services
      - "traefik.http.routers.homebox.service=homebox"
      - "traefik.http.services.homebox.loadbalancer.server.port=7745"
 ```

homebox.env:
```
HBOX_LOG_LEVEL=debug
HBOX_LOG_FORMAT=text
HBOX_WEB_MAX_UPLOAD_SIZE=10
```

### Deployment

Docker (Linux)
