### ISSUE TITLE
Homescreen empty "Failed to search items"

### ISSUE THREAD

**Issue by Saturo78** [sysadminsmedia/homebox#121]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### Homebox Version

Version: v0.12.1

### What is the issue you are experiencing?

Yesterday i switched from v0.10.3. 
I have an issue that after a while the homescreen is empty by clicking on search i get the message "failed to search items"
When i restart the container everything works fine but after a while the issue comes back.

### How can the maintainer reproduce the issue?

The issue occurs after a while of use.

### Deployment

Docker (Linux)

### Deployment Details

Raspberry Pi 4 Computer Modell B, 4GB RAM

**Comment by katosdev** [comment]
I am not able to replicate this one myself. 
@tankerkiller125 please can you attempt to replicate?

**Comment by tankerkiller125** [comment]
How long is a while? I have a testing environment that's been running for 5 days straight so far and I'm not seeing this issue happen. I don't leave the tab open to it though, so maybe something there if you're leaving the tab open?

**Comment by katosdev** [comment]
It seems that this temporarily flashes (like, VERY short period of time) when flicking between menus, but it's barely noticeable to me. Are you able to restart the Pi and rule out any performance / networking issues please?

**Comment by Saturo78** [comment]
I changed it yesterday morning. The error occurred for the first time in the afternoon after about 5 hours. In the meantime, I didn't use homebox and didn't have a tab open. The second time the error occurred this morning when I first used it. With version 0.10.3, which I have been using for the last 2 months, this error did not occur.
Is there anything I can do to help you find the error?

**Comment by katosdev** [comment]
> Is there anything I can do to help you find the error?

Are you able to replicate the issue and then download and share your HAR file please? This hopefully will help us to identify where the call is failing.

**Comment by tankerkiller125** [comment]
> > Is there anything I can do to help you find the error?
> 
> Are you able to replicate the issue and then download and share your HAR file please? This hopefully will help us to identify where the call is failing. 

Before sharing the HAR file please run it through HAR sanitizer https://har-sanitizer.pages.dev/ we don't want access tokens and what not getting leaked to the general Internet.

**Comment by Saturo78** [comment]
After two day the issue is there again.
Here is the HAR file.
[redacted_myurl_Archive [24-07-14 14-12-37].zip](https://github.com/user-attachments/files/16220429/redacted_myurl_Archive.24-07-14.14-12-37.zip)

**Comment by katosdev** [comment]
> After two day the issue is there again. Here is the HAR file. [redacted_myurl_Archive [24-07-14 14-12-37].zip](https://github.com/user-attachments/files/16220429/redacted_myurl_Archive.24-07-14.14-12-37.zip)

Apologies for the delays, there seems to be a lot of errors on your install. Can you please describe how this is configured? 
Are you using a reverse proxy at all?

**Comment by Saturo78** [comment]
I use portainer with this config:

```
version: "3.4"

services:
  homebox:
    image: ghcr.io/hay-kot/homebox:latest
#   image: ghcr.io/hay-kot/homebox:latest-rootless
#   image: ghcr.io/hay-kot/homebox:latest
#   image: ghcr.io/sysadminsmedia/homebox:latest
    container_name: homebox
    restart: always
    environment:
    - HBOX_LOG_LEVEL=info
    - HBOX_LOG_FORMAT=text
    - HBOX_WEB_MAX_UPLOAD_SIZE=10
    - HBOX_OPTIONS_ALLOW_REGISTRATION=false
    volumes:
    - /home/christian/homebox/:/data/
    ports:
      - 3100:7745

volumes:
   homebox-data:
     driver: local
```
and yes i use ngix proxy manager as reverse proxy.
