### ISSUE TITLE
Authorization header or query is required

### ISSUE THREAD

**Issue by dlfinzel** [sysadminsmedia/homebox#134]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### Homebox Version

0.12.1 Build ab3479173735a6946580baee817948513c5f307c

### What is the issue you are experiencing?

Using a very simple installation of Docker Compose + Caddy for a reverse proxy, I was able to get the web application deployed successfully. I am able to register users, but upon logging in, I am immediately logged out after navigating to any page outside of Home.

In the docker container logs, this is displayed dozens of times:
```
ERR ../go/src/app/internal/web/mid/errors.go:31 > ERROR occurred error="authorization header or query is required" req_id=afe67a9cef7c/Hn2n9w8WdR-002177
```

(the request ID is unchanging except for the last 6 digits)

### How can the maintainer reproduce the issue?

I am unsure how to reproduce the issue, since all I did was copy the docker compose sample to my docker host, and bring up the container. I did no customization other than changing the volume to be a host bind mount instead of docker volume.

### Deployment

Docker (Linux)

### Deployment Details

Here is my docker compose file:

```
---
services:
  homebox:
    image: ghcr.io/sysadminsmedia/homebox:latest
    container_name: homebox.apps.[redacted]
    restart: unless-stopped
    environment:
      - HBOX_LOG_LEVEL=info
      - HBOX_LOG_FORMAT=text
      - HBOX_WEB_MAX_UPLOAD_SIZE=10
    networks:
      - [redacted]
    ports:
      - 127.0.0.1:8001:7745
    volumes:
      - /service/docker/container/homebox/data:/data/

networks:
  [redacted]:
    external: true
```

And here is my reverse proxy config (Caddy)

```
inventory.[redacted] {
        reverse_proxy 127.0.0.1:8001 {
                header_up Host {upstream_hostport}
        }
}
```

As far as I am aware, there is nothing out of the ordinary in my deployment environment. the Docker host in question has a dozen other containers working just fine, as does Caddy having a dozen other routes configured.

I tested from my Debian 12 desktop using Firefox AND Chrome, and also from my cell phone (iOS using Opera and Safari)
It matters not where/what I connect from, I get the error in the docker container log, and am immediately logged out.
