### ISSUE TITLE
Header causes UI to lag and GPU usage for tab to spike to 90%

### ISSUE THREAD

**Issue by talha5389** [sysadminsmedia/homebox#225]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### Homebox Version

docker image homebox:0.14.2-rootless

### What is the issue you are experiencing?

Just did a fresh install and after login it was very laggy. Hovering over items in sidebar caused GPU Process to spike to 90% in browser task manager.

Currently using brave browser [Version 1.69.168 Chromium: 128.0.6613.138 (Official Build) (64-bit)])  in Windows 11 23H2

![image](https://github.com/user-attachments/assets/7f94a4f0-2b88-4730-b41a-d7e7785e0f61)

## Workaround

Disable header in profile theming

### How can the maintainer reproduce the issue?

Run new install of homebox. Hover over items. It will spike and cause lag

### Deployment

Docker (Linux)

### Deployment Details

Running using below docker file produced this issue.

```yml
services:
  homebox:
    image: ghcr.io/sysadminsmedia/homebox:0.14.2-rootless
    # image: ghcr.io/hay-kot/homebox:latest
    container_name: homebox
    restart: always
    environment:
      - HBOX_LOG_LEVEL=info
      - HBOX_LOG_FORMAT=text
      - HBOX_WEB_MAX_UPLOAD_SIZE=150
      - HBOX_OPTIONS_ALLOW_REGISTRATION=${HBOX_OPTIONS_ALLOW_REGISTRATION}
      - HBOX_MAILER_HOST=${HBOX_MAILER_HOST}
      - HBOX_MAILER_PORT=${HBOX_MAILER_PORT}
      - HBOX_MAILER_USERNAME=${HBOX_MAILER_USERNAME}
      - HBOX_MAILER_PASSWORD=${HBOX_MAILER_PASSWORD}
      - HBOX_MAILER_FROM=${HBOX_MAILER_FROM}
      - TZ=Asia/Karachi
```
