### ISSUE TITLE
Attachments giving 404 after OS reboot of homebox server host

### ISSUE THREAD

**Issue by talha5389** [sysadminsmedia/homebox#245]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] I can replicate the issue inside the Demo install.

### Homebox Version

0.14.2

### What is the issue you are experiencing?

I had to restart server to apply updates. After restart, all images/attachments of my items are giving 404 error. I am using homebox via traefik proxy but nothing was changed regarding this. I have tried accessing it from different client browsers and different machines but issue occurs on all of them. So something went wrong with server.

One interesting thing is that `img` tag on demo also has access_token parameter present in `src` which my local img tag didn't. Maybe that is what is causing issue
![image](https://github.com/user-attachments/assets/699eaf85-7a9a-44c2-a3af-ed8ff6031690)

## Relevant information which may help

If I inspect devtools, this is the img tag in DOM
```
<img data-v-12ac9995="" class="max-h-[200px] rounded" src="/items/74f49fb9-f7b2-449f-9500-48f067b71db1/attachments/8602f7d5-1ee3-4c8d-9eff-8962148ad0bb">
```

In network, it gives 200 but with content type of `text/html`
![image](https://github.com/user-attachments/assets/1d445900-feb9-448f-bf7a-2ec4813a8fbc)

If I open this directly in browser, it gives 404 page instead with 200 HTTP status code

![image](https://github.com/user-attachments/assets/8b297b69-3ff1-4f70-9d6f-80841fca04b5)

I have even checked data directory for docker and images actually is present on local disk. I even tried uploading new images in case older ones become invalid for some reason but even those are not working.

![image](https://github.com/user-attachments/assets/cb02e0a3-9c52-46bb-ac00-3b4283e2b43f)

Even api request for items does have path to image correctly returned
```
{
    "id": "74f49fb9-f7b2-449f-9500-48f067b71db1",
    "name": "Rj45 crimper",
    "description": "",
    "quantity": 1,
    "insured": false,
    "archived": false,
    "createdAt": "2024-09-19T04:12:23.970282207Z",
    "updatedAt": "2024-09-22T16:44:37.856609211Z",
    "purchasePrice": "0",
    "location": {
        "id": "abd2e77b-9f01-4fec-a54d-4dedc7946c45",
        "name": "Computer table",
        "description": "",
        "createdAt": "2024-09-19T04:06:21.896963324Z",
        "updatedAt": "2024-09-19T04:06:21.896963972Z"
    },
    "labels": [
        {
            "id": "4c67b724-3f12-48ed-ba2b-f815e1021c31",
            "name": "Tools",
            "description": "Hardware Tools",
            "createdAt": "2024-09-15T05:43:28.566982714Z",
            "updatedAt": "2024-09-15T05:43:28.566983003Z"
        },
        {
            "id": "0379666b-3a1f-4d13-82ed-3b8b44a9c492",
            "name": "Networking",
            "description": "Wired/wireless networking components",
            "createdAt": "2024-09-15T05:36:11.059112796Z",
            "updatedAt": "2024-09-15T05:36:11.059113077Z"
        }
    ],
    "imageId": "16caecdb-1084-4ea4-b785-3a3860b53dfa",
    "assetId": "000-013",
    "serialNumber": "",
    "modelNumber": "",
    "manufacturer": "",
    "lifetimeWarranty": false,
    "warrantyExpires": "0001-09-22",
    "warrantyDetails": "",
    "purchaseTime": "0001-09-22",
    "purchaseFrom": "",
    "soldTime": "0001-09-22",
    "soldTo": "",
    "soldPrice": "0",
    "soldNotes": "",
    "notes": "",
    "attachments": [
        {
            "id": "16caecdb-1084-4ea4-b785-3a3860b53dfa",
            "createdAt": "2024-09-22T16:42:49.984281548Z",
            "updatedAt": "2024-09-22T16:42:49.984282243Z",
            "type": "photo",
            "document": {
                "id": "dc78c5e7-de23-4e00-b9c7-c63d83c549d8",
                "title": "PXL_20240919_041048940.MP.jpg",
                "path": "/data/3604b897-76be-47f8-b5f5-6d625a3ce238/documents/4b669a32-f667-4cd2-90a4-bcf7054b03e7.jpg"
            },
            "primary": true
        },
        {
            "id": "8602f7d5-1ee3-4c8d-9eff-8962148ad0bb",
            "createdAt": "2024-09-22T16:44:34.724402783Z",
            "updatedAt": "2024-09-22T16:44:34.724403728Z",
            "type": "photo",
            "document": {
                "id": "d53ded24-92bd-41a4-a686-369d378752ee",
                "title": "IMG_20220322_152434.jpg",
                "path": "/data/3604b897-76be-47f8-b5f5-6d625a3ce238/documents/65aeedbb-bdc1-4e2e-b6bf-9d9bbe429d16.jpg"
            },
            "primary": false
        }
    ],
    "fields": []
}
```

### How can the maintainer reproduce the issue?

Not sure if this will be reproduced on your end. If needed, I can try to launch new homebox instance provided that I will be able to import my existing data in it somehow

### Deployment

Docker (Linux)

### OS Architechture

x86_64 (AMD, Intel)

### Deployment Details

Using docker compose

```
 image: ghcr.io/sysadminsmedia/homebox:0.14.2-rootless
    # image: ghcr.io/hay-kot/homebox:latest
    container_name: homebox
    restart: always
    environment:
      - HBOX_LOG_LEVEL=info
      - HBOX_LOG_FORMAT=text
      - HBOX_WEB_MAX_UPLOAD_SIZE=150
      - HBOX_OPTIONS_ALLOW_REGISTRATION=${HBOX_OPTIONS_ALLOW_REGISTRATION}
      - HBOX_MAILER_HOST=${HBOX_MAILER_HOST}

      - HBOX_MAILER_PORT=${HBOX_MAILER_PORT}
      - HBOX_MAILER_USERNAME=${HBOX_MAILER_USERNAME}
      - HBOX_MAILER_PASSWORD=${HBOX_MAILER_PASSWORD}
      - HBOX_MAILER_FROM=${HBOX_MAILER_FROM}
      - TZ=Asia/Karachi
    volumes:
      #If you use the rootless image, and instead of using named volumes you would prefer using a hostMount directly (e.g., volumes: [ /path/to/data/folder:/data ])
      #you need to chown the chosen directory in advance to the 65532 user (as shown in the Docker example above).
      - /home/homebox/homebox/data:/data/
      # - homebox-data:/data/
    ports:
      - 3100:7745
```
