### ISSUE TITLE
Maintenance view does not appear after upgrade to release v0.15.0

### ISSUE THREAD

**Issue by sgiraz** [sysadminsmedia/homebox#262]
### First Check

- [x] This is not a feature request
- [x] I added a very descriptive title to this issue.
- [x] I used the GitHub search to find a similar issue and didn't find it.
- [x] I searched the documentation, with the integrated search.
- [x] I already read the docs and didn't find an answer.
- [ ] I can replicate the issue inside the Demo install.

### Homebox Version

Version: v0.15.0 ~ Build: f386d1213f51bdbada2746ae0978181561bb447c

### What is the issue you are experiencing?

In Release https://github.com/sysadminsmedia/homebox/releases/tag/v0.15.0 it has been implemented the maintenance view, but while I can see it is working correctly in the Demo https://demo.homebox.software/home, I cannot say the same locally for the dockerized version after the upgrade from the previous release https://github.com/sysadminsmedia/homebox/releases/tag/v0.14.2.

![Image](https://github.com/user-attachments/assets/d911aad5-8fd5-4643-8210-5103ce30dab1)

### How can the maintainer reproduce the issue?

This is my `compose.yml`:

```yaml
services:
  homebox:
#    image: ghcr.io/sysadminsmedia/homebox:latest
    image: ghcr.io/sysadminsmedia/homebox:latest-rootless
    container_name: homebox
    restart: always
    environment:
    - HBOX_LOG_LEVEL=info
    - HBOX_LOG_FORMAT=text
    - HBOX_WEB_MAX_UPLOAD_SIZE=10
    volumes:
      - <insert-here-your-path>:/data
    ports:
      - 3100:7745

volumes:
   homebox-data:
     driver: local
```

You can try it and see if your are able to reproduce it!

>[!Note]
>I replaced the `<insert-here-your-path>` with a real path for my machine

cc @mcarbonne 

### Deployment

Docker (Windows)

### OS Architechture

x86_64 (AMD, Intel)
