### ISSUE TITLE
no matching manifest arm64 v8

### ISSUE THREAD

**Issue by alx-xlx** [sysadminsmedia/homebox#359]
### First Check

- [x] This is not a feature request
- [x] I added a very descriptive title to this issue.
- [x] I used the GitHub search to find a similar issue and didn't find it.
- [x] I searched the documentation, with the integrated search.
- [x] I already read the docs and didn't find an answer.
- [x] I can replicate the issue inside the Demo install.

### Homebox Version

latest

### What is the issue you are experiencing?

```
pi@pi5:~ $ docker compose -f /home/pi/Server8/homebox.yml up -d
[+] Running 0/1
 ⠴ homebox Pulling                                                  1.6s
no matching manifest for linux/arm64/v8 in the manifest list entries
```

### How can the maintainer reproduce the issue?

use the following docker compose file

```
services:
  homebox:
    image: ghcr.io/sysadminsmedia/homebox:latest
#   image: ghcr.io/sysadminsmedia/homebox:latest-rootless
    container_name: homebox
    # restart: always
    environment:
    - HBOX_LOG_LEVEL=info
    - HBOX_LOG_FORMAT=text
    - HBOX_WEB_MAX_UPLOAD_SIZE=10
    volumes:
      - /home/pi/data/homebox/homebox-data:/data/
    ports:
      - 5936:7745
    labels:
      - sablier.enable=true
      - sablier.group=homebox
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7745"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

volumes:
  homebox-data:
    driver: local


```

### Deployment

Docker (Linux)

### OS Architechture

ARM64
