### ISSUE TITLE
Generated QR codes to print ahead result in 'Asset not found' error

### ISSUE THREAD

**Issue by KingDaveRa** [sysadminsmedia/homebox#373]
### First Check

- [x] This is not a feature request
- [x] I added a very descriptive title to this issue.
- [x] I used the GitHub search to find a similar issue and didn't find it.
- [x] I searched the documentation, with the integrated search.
- [x] I already read the docs and didn't find an answer.
- [x] I can replicate the issue inside the Demo install.

### Homebox Version

Version: v0.16.0 ~ Build: 5e81e6010687d8b15cc4bac06e73faedafc735aa

### What is the issue you are experiencing?

I am generating QR code labels, so that I can bulk print, stick them onto things, then scan and add in one go.

However, this isn't working. When I scan the generated QR code for a new item (i.e. it doesn't yet exist) I get the error 'Asset not found'. This was previously working, but I upgraded today. Unfortunately I do not recall which version I had previously, I set Homebox up a few months back and parked the project. But at the time the label URLs definitely worked.

If I scan a QR code for an extant item, it works fine. 

The URL generated is in the form https://{serverhostname}/a/000-000, obviously the number increments for each URL.

### How can the maintainer reproduce the issue?

1. Generate QR codes using the print ahead generator
2. Scan code for new item
3. Error returned.

### Deployment

Docker (Linux)

### OS Architechture

x86_64 (AMD, Intel)

### Deployment Details

My compose file.
```
services:
  homebox:
    image: ghcr.io/sysadminsmedia/homebox:latest
#   image: ghcr.io/sysadminsmedia/homebox:latest-rootless
    container_name: homebox
    restart: always
    environment:
    - HBOX_LOG_LEVEL=info
    - HBOX_LOG_FORMAT=text
    - HBOX_WEB_MAX_UPLOAD_SIZE=10
    volumes:
      - homebox-data:/data/
    ports:
      - 3100:7745

volumes:
   homebox-data:
     driver: local
```

I use nginx as a front end, but it does it via the direct URL into the container as well.
