### ISSUE TITLE
Readonly database error on 0.16.0 to 0.17.1 upgrade (rootless)

### ISSUE THREAD

**Issue by rpavlik** [sysadminsmedia/homebox#449]
### First Check

- [x] This is not a feature request
- [x] I added a very descriptive title to this issue.
- [x] I used the GitHub search to find a similar issue and didn't find it.
- [x] I searched the documentation, with the integrated search.
- [x] I already read the docs and didn't find an answer.
- [x] I can replicate the issue inside the Demo install.

### Homebox Version

0.17.1

### What is the issue you are experiencing?

If I manually launch the rootless docker container via docker-compose (after doing docker-compose down to make sure it's shut down), I get the following error:

```
Creating network "homebox_default" with the default driver
Creating homebox ... done
Attaching to homebox
homebox    | 5:40PM ERR ../go/src/app/app/api/main.go:122 > failed creating schema resources error="sqlite: check foreign_keys pragma: reading schema information attempt to write a readonly database (1544)" driver=sqlite url=/data/homebox.db?_pragma=busy_timeout=2000&_pragma=journal_mode=WAL&_fk=1&_time_format=sqlite
homebox    | panic: sqlite: check foreign_keys pragma: reading schema information attempt to write a readonly database (1544)
homebox    | 
homebox    | goroutine 1 [running]:
homebox    | main.main()
homebox    |    /go/src/app/app/api/main.go:67 +0x70
```

I can switch back to 0.16.0 and it still works.

### How can the maintainer reproduce the issue?

This docker-compose file works fine:

```yml
version: "3.4"

services:
  homebox:
    # image: ghcr.io/hay-kot/homebox:latest
    # image: ghcr.io/hay-kot/homebox:latest-rootless
    image: ghcr.io/sysadminsmedia/homebox:0.16.0-rootless
    container_name: homebox
    restart: unless-stopped
    environment:
    - HBOX_LOG_LEVEL=info
    - HBOX_LOG_FORMAT=text
    - HBOX_WEB_MAX_UPLOAD_SIZE=10
    - TZ=America/Chicago
    # see https://github.com/hay-kot/homebox/issues/906#issuecomment-2130499441
    # - HBOX_STORAGE_SQLITE_URL=/data/homebox.db?_pragma=busy_timeout=2000&_pragma=journal_mode=WAL&_fk=1
    volumes:
      - "/opt/appdata/homebox-data:/data"
    ports:
      - 3100:7745
```

But this one does not, when I change it in-place (that is, there is an existing database, if that matters):

```yml
version: "3.4"

services:
  homebox:
    # image: ghcr.io/hay-kot/homebox:latest
    # image: ghcr.io/hay-kot/homebox:latest-rootless
    image: ghcr.io/sysadminsmedia/homebox:0.17.1-rootless
    container_name: homebox
    restart: unless-stopped
    environment:
    - HBOX_LOG_LEVEL=info
    - HBOX_LOG_FORMAT=text
    - HBOX_WEB_MAX_UPLOAD_SIZE=10
    - TZ=America/Chicago
    # see https://github.com/hay-kot/homebox/issues/906#issuecomment-2130499441
    # - HBOX_STORAGE_SQLITE_URL=/data/homebox.db?_pragma=busy_timeout=2000&_pragma=journal_mode=WAL&_fk=1
    volumes:
      - "/opt/appdata/homebox-data:/data"
    ports:
      - 3100:7745
```

Database is correctly chowned to 65532 - I'm using Ansible to deploy this, see attached, rename to .yml:

- playbook [homebox.yml](https://github.com/user-attachments/files/18322703/homebox.txt)
- template [compose/homebox.docker-compose.yml](https://github.com/user-attachments/files/18322713/homebox.docker-compose.txt)

(I have `appdata` as an inventory variable pointing to `/opt/appdata`)

### Deployment

Docker (Linux)

### OS Architechture

x86_64 (AMD, Intel)
