### ISSUE TITLE
Soft logout makes images / photos disappear

### ISSUE THREAD

**Issue by supaeasy** [sysadminsmedia/homebox#576]
### First Check

- [x] This is not a feature request
- [x] I added a very descriptive title to this issue.
- [x] I used the GitHub search to find a similar issue and didn't find it.
- [x] I searched the documentation, with the integrated search.
- [x] I already read the docs and didn't find an answer.
- [x] I can replicate the issue inside the Demo install.

### Homebox Version

0.17.2

### What is the issue you are experiencing?

After some time (I dont know how long exactly, but rather days than hours) Images do not show anymore. Everything else keeps working fine. Logging out and back in fixes this so it is a small bug, but I think this should not happen. I assume there is some kind of soft logout after a certain time. 

![Image](https://github.com/user-attachments/assets/fdd7dc3d-4d6a-4ab7-a593-d514304128f7)

### How can the maintainer reproduce the issue?

Login and wait at least a day. Maybe more.

### Deployment

Docker (Synology)

### OS Architechture

x86_64 (AMD, Intel)

### Deployment Details

Container Manager (Synology-Docker) v. 24.0.2 (API: 1.43) (previous Versin had same issue)
Deployed via Portainer using this `docker-compose.yaml`

```
services:
  homebox:
    image: ghcr.io/sysadminsmedia/homebox:latest
    container_name: homebox
    restart: always
    environment:
    - HBOX_LOG_LEVEL=info
    - HBOX_LOG_FORMAT=text
    - HBOX_WEB_MAX_UPLOAD_SIZE=10
    volumes:
      - /volume2/docker/homebox/data:/data/
    ports:
      - 3100:7745

volumes:
   homebox-data:
     driver: local
```
