### ISSUE TITLE
Error importing a CSV File

### ISSUE THREAD

**Issue by mherke** [sysadminsmedia/homebox#630]
I am trying to upload a csv file into homebox with 50 items. Creating item manually works fine. Exporting my items and try to import that file gives me:

```
homebox  | 8:00AM ERR ../go/src/app/app/api/handlers/v1/v1_ctrl_items.go:322 > failed to import items error="record on line 2: wrong number of fields"
homebox  | 8:00AM ERR ../go/src/app/internal/web/mid/errors.go:31 > ERROR occurred error="record on line 2: wrong number of fields" req_id=2712b0cd8cfc/BllI5bfFr7-000023
```

According to the docs i need to use a file with only the following standard columns:

- HB.quantity
- HB.name
- HB.asset_id
- HB.description
- HB.insured
- HB.serial_number
- HB.model_number
- HB.manufacturer
- HB.notes
- HB.purchase_from
- HB.purchase_price
- HB.purchase_time
- HB.lifetime_warranty
- HB.warranty_expires
- HB.warranty_details
- HB.sold_to
- HB.sold_time
- HB.sold_price
- HB.sold_notes

trying to use this set of fields:

```
HB.quantity,HB.name,HB.location,HB.asset_id,HB.description,HB.insured,HB.serial_number,HB.model_number,HB.manufacturer,HB.notes,HB.purchase_from,HB.purchase_price,HB.purchase_time,HB.lifetime_warranty,HB.warranty_expires,HB.warranty_details,HB.sold_to,HB.sold_time,HB.sold_price,HB.sold_notes
5,TestImport,Vorratsraum,000-002,,false,,,,,,0,,false,,,,,0
```

returns an error:

> homebox  | 8:09AM ERR ../go/src/app/app/api/handlers/v1/v1_ctrl_items.go:322 > failed to import items error="failed to create location"
> homebox  | 8:09AM ERR ../go/src/app/internal/web/mid/errors.go:31 > ERROR occurred error="failed to create location" req_id=2712b0cd8cfc/BllI5bfFr7-000050

...when i add the location columns to my import file i get again the error "wrong number of fields" .

Question:
- is this a bug or do i use the wrong file header/columns?
- is the a template for the import?

...thanks for your support

----------------------------

I am using:

`Version: v0.18.0 ~ Build: 3a3280466e1c05c0db2956e96f45e8d98e0899c8 `

docker-compose.yaml:

```
services:
  homebox:
    image: ghcr.io/sysadminsmedia/homebox:latest
    container_name: homebox
    restart: always
    environment:
      - HBOX_LOG_LEVEL=info
      - HBOX_LOG_FORMAT=text
      - HBOX_WEB_MAX_UPLOAD_SIZE=10
      - HBOX_MODE=production
      - HBOX_OPTIONS_AUTO_INCREMENT_ASSET=true
    volumes:
      - /home/homebox:/data/
    ports:
      - 3100:7745
networks: {}
```
