### ISSUE TITLE
Migration from "old" Homebox to "new" Homebox

### ISSUE THREAD

**Issue by Kimbaras** [sysadminsmedia/homebox#84]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### Homebox Version

0.10.3 -> 0.11.1

### What is the issue you are experiencing?

First of all, great that someone took over the project, really loving it!

Regarding my issue: I've got a couple of Homebox instances which are running on v0.10.3 (should be latest the original dev released).
I tried to "migrate" them to your version (v0.11.1 as the time of writing this).

I've checked if there were differenced in the Docker Compose and there are not (at least, if I'm not blind and missed something), and updated the image source with yours.
After starting the container I get the following error and the container fails to start.

```
panic: parsing config: parsing config: conf: error assigning to field ReadTimeout: converting '60' to type time.Duration. details: time: missing unit in duration "60"
goroutine 1 [running]:
main.main()
	/go/src/app/app/api/main.go:63 +0x7f
```

So not sure if there is some incompatibility between the twos.
If instead on simply "migrating" the source, some other actions are needed, a couple of directions would be appreciated in order to migrated the data.

Thanks!

### How can the maintainer reproduce the issue?

Could be tricky but basically:

- Deploy one instance from the original repo (using the latest release)
- Add some data
- Edit the compose file changing the image source from

_image: ghcr.io/hay-kot/homebox:latest_

to

_image: ghcr.io/sysadminsmedia/homebox:latest_

- Restart the container
- Observe the errors.

### Deployment

Docker (Linux)

### Deployment Details

Homebox is currently running on a Ubuntu 22.04 LXC container on Proxmox (8.2) host

**Comment by Kimbaras** [comment]
Oh by the way, deploying a new empty instance from scratch using your repo work correctly, so this issue is exclusively related to the "migration" / update from the old repo to this one.

Thanks!

**Comment by tankerkiller125** [comment]
Can you share your existing configuration in terms of the Environment variables?

**Comment by Kimbaras** [comment]
Here it is:

```
version: "3.4"

services:
  homebox:
    image: ghcr.io/hay-kot/homebox:latest
    #image: ghcr.io/sysadminsmedia/homebox:latest
    container_name: PCParts
    restart: unless-stopped
    environment:
    - HBOX_LOG_LEVEL=info
    - HBOX_LOG_FORMAT=text
    - HBOX_WEB_MAX_UPLOAD_SIZE=2048
    - HBOX_WEB_READ_TIMEOUT=60
    - HBOX_WEB_WRITE_TIMEOUT=120
    volumes:
      - /srv/data/:/data/
    ports:
      - 4100:7745
```

It's slight different than the basic example as I'm using a local folder to store the data instead of the volumes, as well as a different port (I'm running a couple of instances on the same host).

As mentioned, if I switch the image source, I get the error mentioned in the issue.

If the same config is deployed on a "clean" environment (say a different port and empty folder) all is working ok and the container starts correctly with your release.

Thanks!

**Comment by tankerkiller125** [comment]
I think what might have happened is that a dependency got updated and might have broken the HBOX_WEB_READ_TIMEOUT and WRITE_TIMEOUT defaulting to seconds.

Adding an actual time to them seems to correct the issue.

So if it was originally in seconds, add an `s` to the end of the existing numbers.

So it would look something like this now (and I've tested this works):
```
version: "3.4"

services:
  homebox:
    #image: ghcr.io/hay-kot/homebox:latest
    image: ghcr.io/sysadminsmedia/homebox:latest
    container_name: PCParts
    restart: unless-stopped
    environment:
    - HBOX_LOG_LEVEL=info
    - HBOX_LOG_FORMAT=text
    - HBOX_WEB_MAX_UPLOAD_SIZE=2048
    - HBOX_WEB_READ_TIMEOUT=60s
    - HBOX_WEB_WRITE_TIMEOUT=120s
    volumes:
      - /srv/data/:/data/
    ports:
      - 4100:7745
```
